"""empty message

Revision ID: 27f0128da58a
Revises: 504b25b49c8d
Create Date: 2023-08-16 17:01:51.864304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f0128da58a'
down_revision = '504b25b49c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_fav', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['planets_fav'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('planets_fav')

    # ### end Alembic commands ###
