"""empty message

Revision ID: 479277364443
Revises: bb36049fbe5b
Create Date: 2023-08-16 17:14:30.306129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479277364443'
down_revision = 'bb36049fbe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_fav', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['users_fav'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('users_fav')

    # ### end Alembic commands ###
