"""empty message

Revision ID: 504b25b49c8d
Revises: 577efc4c7463
Create Date: 2023-08-16 06:36:53.663432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504b25b49c8d'
down_revision = '577efc4c7463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['uid'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
