"""empty message

Revision ID: 72f493a110a8
Revises: 4a9a77820f8d
Create Date: 2023-08-17 18:37:45.751799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f493a110a8'
down_revision = '4a9a77820f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_planets', schema=None) as batch_op:
        batch_op.drop_constraint('fav_planets_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('fav_planets_planet_id_fkey', type_='foreignkey')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_users_fav_key', type_='unique')
        batch_op.drop_column('users_fav')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_planets_fav_key', type_='unique')
        batch_op.drop_column('planets_fav')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_fav', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_planets_fav_key', ['planets_fav'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_fav', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('planets_users_fav_key', ['users_fav'])

    with op.batch_alter_table('fav_planets', schema=None) as batch_op:
        batch_op.create_foreign_key('fav_planets_planet_id_fkey', 'planets', ['planet_id'], ['uid'])
        batch_op.create_foreign_key('fav_planets_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
