"""empty message

Revision ID: 9c8c4c87612a
Revises: d842705dce2a
Create Date: 2023-08-16 17:09:06.517299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8c4c87612a'
down_revision = 'd842705dce2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_fav', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['users_fav'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('users_fav')

    # ### end Alembic commands ###
