"""empty message

Revision ID: 9f6053041093
Revises: 56f21c8bf683
Create Date: 2023-08-16 03:19:39.654852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6053041093'
down_revision = '56f21c8bf683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prueba', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['prueba'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('prueba')

    # ### end Alembic commands ###
