"""empty message

Revision ID: bb36049fbe5b
Revises: 796ba5a51e24
Create Date: 2023-08-16 17:14:02.129417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb36049fbe5b'
down_revision = '796ba5a51e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_fav', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['users_fav'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('planets_fav',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('planets_fav',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('users_fav')

    # ### end Alembic commands ###
