"""empty message

Revision ID: d2fbd2188d3a
Revises: 27f0128da58a
Create Date: 2023-08-16 17:05:51.078778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fbd2188d3a'
down_revision = '27f0128da58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_fav', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['users_fav'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('users_fav')

    # ### end Alembic commands ###
